name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # 只在 main 分支 push 时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-service:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/backend-service:latest

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          docker stop backend-service || true
          docker rm backend-service || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/backend-service:latest
          docker run -d -p 8000:8000 --name backend-service ${{ secrets.DOCKER_USERNAME }}/backend-service:latest
       
